const chalk = require('chalk');

console.log(chalk.blue("Hello Everyone"));
console.log(chalk.blue("WELCOME TO EDUREKA"));
console.log(chalk.underline.red("WELCOME TO EDUREKA"));
console.log(chalk.underline.yellow("WELCOME TO EDUREKA"));
console.log(chalk.green("WELCOME TO EDUREKA"));
console.log(chalk.blue("WELCOME TO EDUREKA"));
console.log(chalk.underline.red("WELCOME TO EDUREKA"));
console.log(chalk.underline.yellow("WELCOME TO EDUREKA"));
console.log(chalk.green("WELCOME TO EDUREKA"));
console.log(chalk.blue("WELCOME TO EDUREKA"));
console.log(chalk.underline.red("WELCOME TO EDUREKA"));
console.log(chalk.underline.yellow("WELCOME TO EDUREKA"));
console.log(chalk.green("WELCOME TO EDUREKA"));
console.log(chalk.blue("WELCOME TO EDUREKA"));
console.log(chalk.underline.red("WELCOME TO EDUREKA"));
console.log(chalk.underline.yellow("WELCOME TO EDUREKA"));
console.log(chalk.green("WELCOME TO EDUREKA"));
console.log(chalk.blue("WELCOME TO EDUREKA"));
console.log(chalk.underline.red("WELCOME TO EDUREKA"));
console.log(chalk.underline.yellow("WELCOME TO EDUREKA"));
console.log(chalk.green("WELCOME TO EDUREKA"));
console.log(chalk.blue("WELCOME TO EDUREKA"));
console.log(chalk.underline.red("WELCOME TO EDUREKA"));
console.log(chalk.underline.yellow("WELCOME TO EDUREKA"));